md "Todos os paises"
cd "Todos os paises"
md "Venezuela"
md "Guiana"
md "Suriname"
md "Guiana Francesa"
md "Brasil"
md "Peru"
md "Colombia"
md "Equador"
md "Paraguai"
md "Uruguai"
md "Argentina"
md "Chile"
md "Bolivia"
cd "Brasil"
md "Mato Grosso"
md "Mato Grosso do Sul"
md "Goias"
md "Maranhao"
md "Piaui"
md "Ceara"
md "Rio Grande do Norte"
md "Pernambuco"
md "Paraiba"
md "Sergipe"
md "Alagoas"
md "Bahia"
md "Amazonas"
md "Roraima"
md "Amapa"
md "Para"
md "Tocantins"
md "Rondonia"
md "Acre"
md "Parana"
md "Rio Grande do Sul"
md "Santa Catarina"
md "Sao Paulo"
md "Rio de Janeiro"
md "Espirito Santo"
md "Minas Gerais"