md "Todos os clubes"
cd "Todos os clubes"
md "Serie A"
md "Serie B"
cd "Serie A"
md "Palmeiras"
md "Flamengo"
md "Atletico Mineiro"
md "Gremio"
md "Sao Paulo"
md "Fluminense"
md "Internacional"
md "Santos"
md "Athletico Paranaense"
md "Corinthians"
md "Bragantino"
md "Fortaleza"
md "Bahia"
md "Ceara"
md "Cuiaba"
md "Atletico Goianense"
md "America Mineiro"
md "Juventude"
md "Sport Recife"
md "Chapecoense"
cd..
cd "Serie B"
md "Avai"
md "Nautico"
md "Remo"
md "Operario"
md "Cruzeiro"
md "Vasco da Gama"
md "CRB"
md "Vila Nova"
md "Brusque"
md "Botafogo"
md "Coritiba"
md "Vitoria"
md "Londrina"
md "CSA"
md "Sampaio Correa"
md "Ponte Preta"
md "Guarani"
md "Confianca"
md "Brasil-RS"
md "Goias"